# MCU name
MCU = atmega32u4

# Bootloader selection
BOOTLOADER = atmel-dfu

RGB_MATRIX_DRIVER = WS2812

AUTO_SHIFT_ENABLE = no
CAPS_WORD_ENABLE = no
COMBO_ENABLE = yes
LEADER_ENABLE = no
KEY_OVERRIDE_ENABLE = yes
SEND_STRING_ENABLE = yes
TAP_DANCE_ENABLE = no

EXTRAFLAGS += -flto
